name: aciar
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - ipywidgets
  - xarray
  - rasterio
  - rioxarray
  - dask
  - netcdf4
  - scipy
  - pandas
  - geopandas
  - matplotlib
  - cartopy
  - esgf-pyclient
  - geocube
  - ipywidgets
  - elapid
  - pip:
      - chelsa-cmip6
      - pyModis