name: sdm-toolbox
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - ipywidgets
  - jupyterlab
  - xarray
  - rasterio
  - rioxarray
  - dask
  - netcdf4
  - scipy
  - pandas
  - geopandas
  - matplotlib
  - cartopy
  - esgf-pyclient
  - geocube
  - geowombat
  - elapid
#   - pip:
#       - chelsa-cmip6
#       - pyModis